
import cv2
import numpy as np
import pyvista as pv
from dataclasses import dataclass
from pathlib import Path
from PIL import Image
from matplotlib import pyplot as plt
from sklearn.cluster._hdbscan import hdbscan
from sklearn.preprocessing import StandardScaler
from tifffile import tifffile

# TODO: Boost vibrance of images, using the background mask to do so

class PostProcessor:
    """
    Processes stacked TIFF images generated by FrameStack.

    This class provides functionality for processing stacked images,
    including downsampling, segmentation, vignette removal, background
    neutralization, and dynamic range adjustment.
    """

    @dataclass(frozen=True)
    class StackedImageInputs:
        data_directory: Path
        verbosity: int = 1

    def __init__(self, **kwargs):

        self.inputs = self.StackedImageInputs(**kwargs)
        self.rgb_raw = self._load_from_tiff().astype(np.float64)
        self.rgb_processing = self.rgb_raw.copy().astype(np.float64)
        self.background_mask = None

        # Initialise processing metadata
        self.processing_details = {
            "dynamic_range_boosted": 0,
            "background_neutralised": 0,
            "noise_reduced": 0,
            "vignette_corrected": 0,
        }

    def align_channel_histogram(self, green_weight=0.99):
        """Aligns the cumulative distribution of pixel intensity across RGB channels.

        The two darker channels are shifted to match the  statistical distribution
        of the brightest channel (the reference).

        For the green channel specifically, a weighting factor is applied to blend the
        original data with the matched distribution, to avoid a strong green signal,
        which is typically induced by signal noise from the sensor.

        Args:
            green_weight (float, optional): The blending factor for the green channel.
                A value of 1.0 fully replaces the channel with matched data, while
                0.0 keeps the original. Defaults to 0.99.

        Returns:
            self: The instance with updated 'rgb_processing' (aligned channel histogram distributions).

        Raises:
            ValueError: If green_weight is outside the range [0.01, 1.0].
        """

        # gren_weight must be in an appropriate range!
        if not (0.0 <= green_weight <= 1.0):
            error_msg = f"Invalid green_weight: {green_weight}. Must be between 0.0 and 1.0."
            raise ValueError(error_msg)

        print("Aligning CDF of RGB channels...")

        # Identify target channel (the brightest mean!)
        # The remaining two channels will be mapped to this channel
        rgb_img = self.rgb_processing.astype(np.float64)

        if self.inputs.verbosity > 0:
            print("Displaying histogram for unmatched channels")
            self._generate_histogram()

        rgb_means = np.nanmean(np.where(rgb_img > 0, rgb_img, np.nan), axis=(0, 1))
        idx_brightest_mean = np.argmax(rgb_means)
        reference_channel = rgb_img[:, :, idx_brightest_mean]
        channel_indices = [0, 1, 2]
        channel_indices.pop(idx_brightest_mean)

        for idx_channel in channel_indices:

            # Calculate the fully matched channel
            matched = self._match_channels(rgb_img[:, :, idx_channel], reference_channel)

            # Apply the weight only if the current channel is g (index 1)
            if idx_channel == 1:
                rgb_img[:, :, 1] = (matched * green_weight) + (rgb_img[:, :, 1] * (1 - green_weight))
            else:
                rgb_img[:, :, idx_channel] = matched

        self.rgb_processing = np.clip(rgb_img, 0, 255).astype(np.float64)

        if self.inputs.verbosity > 0:
            print("Displaying histogram for matched channels")
            self._generate_histogram()

        channel_str = ['red', 'green', 'blue']
        print(f"... CDF alignment complete. All channels now share the {channel_str[idx_brightest_mean]} distribution")

        return self

    def neutralise_background_colour(self):
        """
        Normalises image white balance by anchoring RGB channels to the brightest background
        channel intensity.

        TODO: Assess if it would be best to always anchor this to the blue channel.

        Calculates per-channel scaling factors based on the background's
        distance from pure white (255). It then applies these factors to the inverted
        color space to align the dimmer background intensities with the brightest channel.

        Returns:
            self: The instance with updated 'rgb_processing' and corrected white balance.
        """

        if self.background_mask is None:
            self._extract_background_with_segmentation()

        print("Neutralising background colour...")

        # Note that background mask is a 3D array
        rgb_background = (self.rgb_processing * self.background_mask)

        # Must be 64 bit to maintain precision when computing large sums, like mean average
        rgb_background.astype(np.float64)

        rgb_means = np.nanmean(np.where(rgb_background > 0, rgb_background, np.nan), axis=(0, 1))
        index_brightest_mean = np.argmax(rgb_means)
        k_colour_correct = (255 - rgb_means[index_brightest_mean]) / (255 - rgb_means)

        self.rgb_processing = 255.0 - k_colour_correct * (255.0 - self.rgb_processing)
        self.rgb_processing = np.clip(self.rgb_processing, 0, 255).astype(np.float64)

        print("... background colour neutralising")

        if self.inputs.verbosity > 0:
            plt.figure(figsize=(16, 12))
            plt.imshow(self.rgb_processing / 255.0)
            plt.show()

        return self

    def _generate_histogram(self):
        """Generates an RGB histogram and normalised CDF plot for diagnostics.

        Visualises channel distribution on a semi-log scale to identify clipping,
        offsets, or exposure imbalances in the current image state.

        Returns:
            self: The current instance of the class.
        """

        print("Generating RGB Histogram Diagnostic...")

        channel_labels = ['red', 'green', 'blue']
        line_colours = ['r','g','b']

        plt.figure(figsize=(10, 6))
        plt.title("Channel Histogram")
        plt.xlabel("Pixel Intensity [0-255]")
        plt.ylabel("Frequency [log]")

        for i in range(len(channel_labels)):

            # Calculate histogram & plot on semi-log axes
            hist, bins = np.histogram(self.rgb_processing[:, :, i].ravel(), bins=256, range=(0, 256))
            plt.semilogy(bins[:-1], hist, color=line_colours[i],
                         alpha=0.8,
                         label=f'{channel_labels[i].capitalize()} Hist'
                         )

            # Calculate cumulative distribution function & normalise by peak of histogram for visualisation purposes
            cumulative_dist = hist.cumsum()
            cumulative_dist_normalised = cumulative_dist * (hist.max() / cumulative_dist.max())
            plt.plot(bins[:-1], cumulative_dist_normalised, color=line_colours[i], linestyle='--', alpha=0.3)

        plt.legend(loc='upper right')
        plt.grid(True, which="both", ls="-", alpha=0.2)
        plt.xlim([0, 256])

        print("Close the plot window to continue...")

        plt.show()

        return self

    @staticmethod
    def _match_channels(input_channel, target_channel):
        """Matches the histogram of an input channel to a target reference channel.

        This is a static method, not relying on any data from an instance.

        This method performs the following steps:
            1. Computes the Cumulative Distribution Function (CDF) for both channels.
            2. Normalises the CDFs to a [0, 1] range.
            3. Creates a Look-Up Table (LUT) by interpolating the input CDF values
               against the target's intensity distribution.
            4. Re-maps the original input pixels to their new intensities using the LUT.

        Args:
            input_channel (np.ndarray): The source channel to transform.
            target_channel (np.ndarray): The reference  channel providing the target distribution.

        Returns:
            np.ndarray: The input channel reshaped and re-mapped to match the
                target histogram.
        """

        # Calculate the CDF of the reference channel
        unique_input_pixel_intensities, input_counts = np.unique(input_channel.ravel(), return_counts=True)
        unique_target_pixel_intensities, target_counts = np.unique(target_channel.ravel(), return_counts=True)

        # Normalise the CDFs
        input_cdf_normalised = np.cumsum(input_counts).astype(np.float64) / input_channel.size
        target_cdf_normalised = np.cumsum(target_counts).astype(np.float64) / target_channel.size

        # Create a look-up table to map the input distribution to the target distribution
        input_to_target_map_lut = np.interp(input_cdf_normalised,
                                            target_cdf_normalised, unique_target_pixel_intensities)

        # Map the input channel to the mapping look up table
        # The query of points is input_channel.ravel() (flattened to a 1D array)
        # The reference values are the pixels in unique_input_pixel_intensities, which are mapped to the target outputs via the input_to_target_map_lut
        matched_channel = np.interp(input_channel.ravel(), unique_input_pixel_intensities, input_to_target_map_lut).reshape(input_channel.shape)

        return matched_channel

    def remove_vignette(self, strength=1.0, degree=2):
        """Corrects radial illumination gradients using a masked polynomial fit.

        Models the background curvature as a function of squared radius (r^2)
        using Ordinary Least Squares. The resulting profile is used to
        flatten the intensity across all image channels.

        Args:
            strength (float): Intensity of the correction; with 1.0 being the strongest (default value).
            degree (int): Radial polynomial degree (even integers, e.g., 2, 4). Default is 2.

        Returns:
            self: instance with updated 'rgb_processing'
        """

        if self.background_mask is None:
            self._extract_background_with_segmentation()

        print("Removing vignette...")

        rgb = self.rgb_processing.copy().astype(np.float64)
        rgb_curvature_corrected = np.empty_like(rgb)
        height, width, n_channels = rgb.shape

        y_centre = (height - 1) / 2.0
        x_centre = (width - 1) / 2.0

        y_grid, x_grid = np.mgrid[0:height, 0:width]

        # r2_grid = (x_grid - x_centre) ** 2 + (y_grid - y_centre) ** 2

        x_norm = (x_grid - x_centre) / x_centre
        y_norm = (y_grid - y_centre) / y_centre
        r2_grid = x_norm ** 2 + y_norm ** 2

        # The background mask is in 3d, so it needs to be flattened to 2d. A check is added for robustness
        if self.background_mask.ndim == 3:
            mask_2d = np.any(self.background_mask, axis=-1)
        else:
            mask_2d = self.background_mask

        # Re-order mask to be a 1d array
        mask_1d = mask_2d.flatten() > 0

        # Generate features matrix, with columns representing each radial power
        radial_powers = range(1, (degree // 2) + 1)
        features = [np.ones_like(x_norm), x_norm, y_norm]
        for p in radial_powers:
            features.append(r2_grid ** p)

        # The design matrix is fed into the least squares solver
        design_matrix = np.stack(features, axis=-1).reshape(-1, len(features))
        design_matrix_masked = design_matrix[mask_1d]

        # Fit and apply curvature corrections for each channel
        for i in range(n_channels):

            single_channel_1d = rgb[:, :, i].reshape(-1)
            single_channel_1d_masked = single_channel_1d[mask_1d]

            # Solve least-squares to find coefficients mapping each co-ordinate from background curvature to rgb data.
            # These fitting coefficients match the form of the equation z = a + b*r^2 + c*r^4 ...
            # They have the following relationship:
            # design_matrix_masked * fitting_coefficients = single_channel_1d_masked
            fitting_coefficients, *_ = np.linalg.lstsq(design_matrix_masked, single_channel_1d_masked, rcond=None)

            # Calculate the background model for the entire image by performing a dot product (@)
            curvature_correction_1d = design_matrix @ fitting_coefficients
            curvature_correction = curvature_correction_1d.reshape(height, width)

            # Create a 2D boolean mask from the first channel if it's 3D
            if self.background_mask.ndim == 3:
                mask_2d = self.background_mask[:, :, 0] > 0
            else:
                mask_2d = self.background_mask > 0

            # Apply the mean normalisation using the 2D mask. Calculate the mean only from the pixels designated as background
            # TODO: Is there a better way to compute the offsets? (future release)
            mean_curvature = np.mean(curvature_correction[mask_2d])
            curvature_offset = curvature_correction - mean_curvature

            # Subtract the fitted curvature from the original channel
            rgb_curvature_corrected[:, :, i] = rgb[:, :, i] - (strength * curvature_offset)

        # Clip data, store as 64 bit, save in Self
        rgb_curvature_corrected = np.clip(rgb_curvature_corrected, 0, 255)
        self.rgb_processing = rgb_curvature_corrected.astype(np.float64)

        print("... process completed")

        if self.inputs.verbosity > 0:
            fig, ax = plt.subplots(1, 2, figsize=(20, 10))
            ax[0].imshow(self.rgb_processing.astype(np.uint8))
            ax[0].set_title("Original")
            ax[1].imshow(rgb_curvature_corrected)
            ax[1].set_title("Vignette Removed (Masked Fit)")
            plt.show()

        return self

    def boost_dynamic_range(self, gamma: float=4):

        # TODO: Make this function more comprehensive, by adding Uses Arcsinh-like scaling and local contrast enhancement (future release)

        self.rgb_processing = self._adjust_gamma(self.rgb_processing,gamma=gamma)

        # Store results
        if self.inputs.verbosity > 0:
            plt.figure(figsize=(16, 12))
            plt.imshow(self.rgb_processing.astype(np.uint32))
            plt.show()

        return self

    def save_image_as_tiff(self):
        """Saves processed RGB data to TIFF. Data is converted from float32, used for processing, to 16bit uint8, for TIFF format"""

        save_data = np.round(np.clip(self.rgb_processing.astype(np.float32), 0, 255) * 257).astype(np.uint16)
        save_path = self.inputs.data_directory / "outputs" / "processed_rgb.tiff"
        tifffile.imwrite(save_path,save_data)

        return self

    def _load_from_tiff(self):
        """Loads the stacked TIFF as a float64 NumPy array"""

        target_file_path = self.inputs.data_directory / "outputs" / "processing_stacked_frame_rgb.tiff"
        if not target_file_path.exists():
            raise FileNotFoundError(f"Stacked image not found: {target_file_path}")
        print(f"Loading stacked image: {target_file_path}")

        with Image.open(target_file_path) as img:
            return np.array(img).astype(np.float64)

    def _extract_background_with_segmentation(self):
        """
        Segments the image using HDBSCAN on color and spatial features to isolate the background.

        This method downsamples the raw RGB data, applies gamma correction, and clusters
        pixels based on normalized 5D features (R, G, B, X, Y). It identifies the
        background by finding the most frequent cluster label present along the image
        edges. The final background mask is stored in `self.background_mask`.

        Returns:
            self: The instance with self.background_mask updated.
                  (1 = background pixel, 0 = non-background pixel).
        """

        # These settings change how the background segmentation process runs, and for now they will be kept as default values
        # TODO: Add the ability to tweak the background segmentation settings (future release)
        downsample_factor = 20
        gamma = 6
        cluster_sensitivity = 5E-4

        print("Extracting background with segmentation...")

        # Image is downsampled to reduce computational effort
        rgb = self._downsample_with_binning(image=self.rgb_processing, downsample_factor=downsample_factor)
        rgb = self._adjust_gamma(image=rgb, gamma=gamma)
        h, w, c = rgb.shape
        rgb_pixels = rgb.reshape(-1, c)

        y_coords, x_coords = np.indices((h,w))
        xy_coords_grid = np.stack(arrays=(x_coords, y_coords), axis=-1)
        xy_coords_1d_array = xy_coords_grid.reshape(-1,2)

        # Normalise co-ordinates and multiply by 255 to be the same order of magnitude as RGB data
        xy_coords_1d_array[:,0] = (xy_coords_1d_array[:,0]/xy_coords_1d_array[:,0].max())*255
        xy_coords_1d_array[:,1] = (xy_coords_1d_array[:,1]/xy_coords_1d_array[:,1].max())*255

        # Combine into a single array with 5 columns: R,G,B,X,Y
        pixel_features_5d = np.column_stack((rgb_pixels, xy_coords_1d_array))

        print("... running HDBSCAN to cluster and label image features")

        # Scale features & run HDBSCAN
        X = StandardScaler().fit_transform(pixel_features_5d)
        cluster_threshold = round(len(xy_coords_1d_array) * cluster_sensitivity)
        clusters = hdbscan.HDBSCAN(min_cluster_size=cluster_threshold, min_samples=cluster_threshold)
        labels_1d = clusters.fit_predict(X)
        labels_xy = np.array(labels_1d).reshape(h,w)

        print(f"... image segmented into {len(np.unique(labels_1d))-1} clusters")

        if self.inputs.verbosity > 1:
            plt.figure(figsize=(16, 12))
            plt.hist(labels_1d)
            plt.show()

        # Labels are reverted to the image scale so that the mask can be applied to the original image
        labels_xy_rescale = self._revert_image_scale(labels_1d)

        # TODO: Make the backgound identification process more robust, for example using the histogram in conjunction with the edge process (future release)

        # Get unique values and their frequencies
        values, counts = np.unique(labels_1d, return_counts=True)

        # Find the index of the maximum count and update the background mask assuming it is the most common pixel
        index = np.argmax(counts)
        background_label = values[index]
        background_mask_single_channel = (labels_xy_rescale == background_label)
        self.background_mask = np.stack([background_mask_single_channel] * 3, axis=-1)

        print("... background extraction complete!")

        if self.inputs.verbosity > 0:
            plt.figure(figsize=(16, 12))
            plt.imshow(self.background_mask)
            plt.show()

        if self.inputs.verbosity > 1:
            point_cloud = pv.PolyData(rgb_pixels)
            point_cloud["ClusterID"] = labels_1d
            plotter = pv.Plotter()
            plotter.add_points(point_cloud, point_size=2)
            plotter.show()

        return self

    def _revert_image_scale(self,image: np.ndarray) -> np.ndarray:
        """Rescales image to rgb_raw dimensions using nearest-neighbor interpolation"""

        target_h, target_w, _ = self.rgb_raw.shape
        resized_image = cv2.resize(image.astype(np.uint16), (target_w, target_h), interpolation=cv2.INTER_NEAREST)

        return resized_image

    @staticmethod
    def _adjust_gamma(image: np.ndarray, gamma: float) -> np.ndarray:
        """
        Applies power-law transformation: V_out = V_max * (V_in / V_max)^gamma.
        Args: image (np.ndarray), gamma (float).
        Returns: np.ndarray (float32).
        """

        image_gamma_corrected = image.max() * (image/image.max())**gamma

        return image_gamma_corrected

    @staticmethod
    def _downsample_with_binning(image: np.ndarray, downsample_factor: int) -> np.ndarray:
        """
        Downsamples a 3D image array via block averaging. Divides the image into (n x n) blocks and replaces each with its mean value.
        Args:
            image: NumPy array of shape (H, W, C) to be downsampled.
            downsample_factor: Integer scale factor for dimension reduction.
        Returns:
            np.ndarray: A new downsampled array of shape (H//n, W//n, C).
        Raises:
            TypeError: If downsample_factor is not an integer.
            ValueError: If downsample_factor is less than 1.
        """

        if not isinstance(downsample_factor, int):
            raise TypeError(f"Downsample factor must be an integer, got {type(downsample_factor).__name__}")

        if downsample_factor < 1:
            raise ValueError(f"Downsample factor must be at least 1: {downsample_factor}")

        # If factor is 1, no processing is required.
        if downsample_factor == 1:
            return image

        # Crop image to be a multiple of the downsample factor in height/width dimensions.
        h, w, c = image.shape
        image_cropped = image[:h - (h % downsample_factor), :w - (w % downsample_factor), :c]

        # Get dimensions of the cropped image.
        h_crop, w_crop, c = image_cropped.shape

        # Reshape the image to move the pixels to be averaged into separate dimensions.
        # Then average across those dimensions to produce the downsampled image.
        image_reshaped = image_cropped.reshape(
            h_crop // downsample_factor, downsample_factor,
            w_crop // downsample_factor, downsample_factor,
            c
        )

        image_downsampled = image_reshaped.mean(axis=(1, 3), dtype=np.float32)

        return image_downsampled

if __name__ == "__main__":
    test_image = PostProcessor(data_directory=Path(r"D:\_Local\OneDrive\Astronomy\StarTrack\dev\raw_data_horsehead"), verbosity=0)
    test_image.remove_vignette()
    test_image.align_channel_histogram()
    test_image.neutralise_background_colour()
    test_image.boost_dynamic_range(gamma=7)
    test_image.save_image_as_tiff()





